export default [
  {
    url: '/project/realms/',
    title: 'Realms',
    description: 'DAO management platform on Solana.',
    stack: 'next, typescript, web3',
    link: 'https://realms.today',
    logo: 'assets/images/projects/realms/logo-m.svg',
    background: 'bg-brand-realms',
    color: 'text-white',
  },
  {
    url: '/project/pali-wallet/',
    title: 'Pali Wallet',
    description: 'A Non-Custodial Crypto Wallet for Syscoin.',
    stack: 'react, typescript, web3',
    link: 'https://paliwallet.com/',
    logo: '/assets/images/projects/pali-wallet/logo-m.png',
    background: 'bg-brand-syscoin',
    color: 'text-white',
  },
  {
    url: '/project/stays-master-system/',
    title: 'Stays Master System',
    description: 'Property management system for vacation rentals.',
    stack: 'node, mongodb, docker',
    link: 'https://stays.cc/web/index',
    logo: '/assets/images/projects/stays-master-system/logo-m.png',
    background: 'bg-brand-staysmastersystem',
    color: 'text-white',
  },
];