export default [
  {
    url: '/project/stays/',
    title: 'Stays',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    stack: 'node, mongodb, docker, jquery',
    link: 'https://stays.net/',
    logo: '/assets/images/projects/stays/logo-m.svg',
    background: 'bg-gray-100',
    color: 'text-white',
  },
  {
    url: '/project/stays-master-system/',
    title: 'Stays Master System',
    description: 'Property management system for vacation rentals.',
    stack: 'node, mongodb, docker',
    link: 'https://stays.cc/web/index',
    logo: '/assets/images/projects/stays-master-system/logo-m.png',
    background: 'bg-brand-staysmastersystem',
    color: 'text-white',
  },
  {
    url: '/project/pali-wallet/',
    title: 'Pali Wallet',
    description: 'A Non-Custodial Crypto Wallet for Syscoin.',
    stack: 'react, typescript, redux',
    link: 'https://paliwallet.com/',
    logo: '/assets/images/projects/pali-wallet/logo-m.png',
    background: 'bg-brand-syscoin',
    color: 'text-white',
  },
];